name: Skip auto shutdown request

body:

- type: markdown
  attributes:
    value: |
      Please provide change details
      
- type: dropdown
  id: download
  attributes:
    label: Business area
    options:
      - cft
      - cross-cutting
  validations:
    required: true
    
- type: dropdown
  id: Enviornment
  attributes:
    label: Environment
    multiple: true
    options:
      - Sandbox
      - AAT / Staging
      - preview/dev
      - test/perftest
      - demo
      - ithc
  validations:
    required: true
      
- type: input
  id: Start_Date
  attributes:
    label: Change_Start_Date
    description: "Change start date"
    placeholder: "MM/DD/YYYY"
  validations:
    required: true
    
- type: input
  id: End_Date
  attributes:
    label: Change_End_Date
    description: "Change end date"
    placeholder: "MM/DD/YYYY"
  validations:
    required: true
