name: AKS Auto Start

on:
  workflow_dispatch:
  schedule:
    # Run everyday
    # - cron: '30 7 * * *' # Everyday at 7:30am UTC (Will enable after tested)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: AKS Auto Start
        run: ./scripts/aks-auto-start.sh
      - name: Tests
        run: ./scripts/tests.sh
